# Site settings
title: Stream-Of-Consciousness
email: jreed91@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A daily stream of content from the mind of Jacob Reed.
# baseurl: "/jacobreed" # the subpath of your site, e.g. /blog/
url: "http://jacobreed.me" # the base hostname & protocol for your site
twitter_username: jreed91
github_username:  jreed91
baseurl: ""

paginate: 5

# Build settings
markdown: kramdown
include:
  - .nojekyll
exclude:
  - "bower_components"
  - "bower.json"
  - "node_modules"
  - "package.json"
  - "Gruntfile.coffee"
  - "Rakefile"
gems: [neat,bourbon,bitters]